DISPLAY_I2C_BUS = 0 
RS485_PORT = "/dev/ttyS4" 
VAISALA_TIMEOUT = 2 
VAISALA_PARITY = 'N' 
VAISALA_BAUDRATE = 19200 
VAISALA_STOPSBITS = 1 
VAISALA_BYTESIZE = 8

OID = "heim01"
SENSOR1_OID = "vts01"
SENSOR1_OID = "vts02"